-- inspired by https://www.lazyvim.org/plugins/treesitter
return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    lazy = false,
    opts = {
        -- LazyVim config for treesitter
        indent = { enable = true },
        highlight = { enable = true },
        folds = { enable = true },
        ensure_installed = {
            "bash",
            "c",
            "c_sharp",
            "cmake",
            "cpp",
            "css",
            "dockerfile",
            "gitcommit",
            "gitignore",
            "hcl",
            "html",
            "htmldjango",
            "java",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "php",
            "python",
            "query",
            "regex",
            "sql",
            "terraform",
            "toml",
            "typescript",
            "vim",
            "vimdoc",
            "yaml",
        },
    },
}
