return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    lazy = false,
    config = function()
        local treesitter = require("nvim-treesitter")

        treesitter.install({
            "bash",
            "c",
            "c_sharp",
            "cmake",
            "cpp",
            "css",
            "dockerfile",
            "gitcommit",
            "gitignore",
            "hcl",
            "html",
            "htmldjango",
            "java",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "php",
            "python",
            "query",
            "regex",
            "sql",
            "terraform",
            "toml",
            "typescript",
            "vim",
            "vimdoc",
            "yaml",
        })
    end,
}
